import Head from 'next/head'
import { Inter } from 'next/font/google'
import * as React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // const handleAddUser = async () => {
  //   try {
  //     const response = await fetch('/api/route', {
  //       method: 'POST',
  //       headers: {
  //         'Content-Type': 'application/json'
  //       },
  //       body: JSON.stringify({
  //         email: 'example@example.com'
  //       })
  //     })
  
  //     if (response.ok) {
  //       const data = await response.json()
  //       console.log('User added:', data)
  //     } else {
  //       console.error('Failed to add user:', response.statusText)
  //     }
  //   } catch (error) {
  //     console.error('Failed to add user:', error)
  //   }
  // }

  const handleCreateAccount = () => {
    router.push('/start')
  }

  return (
    <>
      <Head>
        <title>Find a Gamer Friend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Box
          display="flex"
          alignItems="center"
          justifyContent="center"
          height="100vh"
          bgcolor="#000"
        >
        <Box maxWidth={1000} width="100%" px={2}>
          <Stack
            direction={{ xs: "column", md: "row" }}
            spacing={{ xs: 10, md: 30 }}
            justifyContent="center"
            alignItems="center"
          >
            <Box color="#fff" textAlign={{ xs: "center", md: "left" }}>
              <Typography variant="h4" gutterBottom>
                Header of Text
              </Typography>
              <Typography variant="body1" gutterBottom>
                Smaller sub header paragraph of text
              </Typography>
              <Button variant="contained" color="primary" style={{ marginTop: '14px' }} onClick={handleCreateAccount}>
                Jump In
              </Button>
            </Box>
            <Box display="flex" justifyContent="center" alignItems="center">
              <img
                src={
                  "https://fastly.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI"
                }
                alt="Example"
                style={{ maxWidth: "100%" }}
              />
            </Box>
          </Stack>
        </Box>
      </Box>

        <Box
        display="flex"
        alignItems="center"
        justifyContent="center"
        height="100vh"
        bgcolor="#fff"
        >

          <Grid item xs={12} md={12}>
          <Box color="#000" textAlign={"center"}>
              <Typography variant="h4" gutterBottom>
                Header of Text
              </Typography>
              <Typography variant="body1" gutterBottom>
                Smaller sub header paragraph of text
              </Typography>
            </Box>
          </Grid>
        </Box>

        <Box
        display="flex"
        alignItems="center"
        justifyContent="center"
        height="100vh"
        bgcolor="#000"
        >
        <p>testing</p>
        </Box>
      </main>
    </>
  )
}
